import { Button, withStyles } from "@material-ui/core"
import { green } from "@material-ui/core/colors"
import Head from "next/head"
import Link from "next/link"
import Header from "../src/Header"
import styles from "../styles/rpkg.module.css"
// @ts-expect-error
import RpkgImage from "../public/rpkg-in-action.png"
import IdealImage from "../src/IdealImage"

interface DownloadButtonProps {
    versionId: string
}

const ColorButton = withStyles((theme) => ({
    root: {
        color: theme.palette.getContrastText(green[500]),
        backgroundColor: green[300],
        "&:hover": {
            backgroundColor: green[500],
        },
    },
}))(Button)

function DownloadButton({ versionId }: DownloadButtonProps) {
    return (
        <Link href={`/tools/rpkg/rpkg_v${versionId}.zip`}>
            <ColorButton variant="outlined">Download v{versionId}</ColorButton>
        </Link>
    )
}

export default function Rpkg() {
    return (
        <div className={"container"}>
            <Head>
                <title>Notex.app - RPKG Tool</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <Header />

            <main className={"main"}>
                <h1 className={"title"}>RPKG</h1>
                <h2 className={styles["is-gray"]}>
                    Developed by{" "}
                    <span className={styles["is-not-gray"]}>[REDACTED]</span>{" "}
                    and hosted by Notex.
                </h2>
                <DownloadButton versionId="2.9" />
                <IdealImage
                    img={RpkgImage}
                    alt="A photo of RPKG in action."
                />
            </main>
        </div>
    )
}
