import React from "react"
import {
    Accordion,
    AccordionDetails,
    AccordionSummary,
    Button,
    createMuiTheme,
    withStyles,
    ThemeProvider,
} from "@material-ui/core"
import { green } from "@material-ui/core/colors"
import Head from "next/head"
import Link from "next/link"
import Header from "../src/Header"
import dynamic from "next/dynamic"
import { latest, RpkgVersion, versions } from "../src/RpkgVersions"
import { renderToString } from "react-dom/server"
import ExpandMoreIcon from "@material-ui/icons/ExpandMore"

const RpkgImage = dynamic(() => import("../src/RpkgImage"))

interface DownloadButtonProps {
    versionId: string
}

const darkTheme = createMuiTheme({
    palette: {
        type: "dark",
    },
    typography: {
        fontFamily:
            "-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;",
    },
    overrides: {
        MuiButton: {
            root: {
                marginBottom: "20px",
            },
        },
    },
})

const ColorButton = withStyles((theme) => ({
    root: {
        color: theme.palette.getContrastText(green[500]),
        backgroundColor: green[500],
        "&:hover": {
            backgroundColor: green[700],
        },
        marginBottom: "20px",
        letterSpacing: "0em",
    },
}))(Button)

function DownloadButton({ versionId }: DownloadButtonProps) {
    return (
        <Link href={`/tools/rpkg/rpkg_v${versionId}.zip`}>
            <ColorButton variant="outlined">
                <b>Download v{versionId}</b>
            </ColorButton>
        </Link>
    )
}

export default function Rpkg({
    versions,
    latest,
}: {
    versions: (RpkgVersion & { changelog: string })[]
    latest: RpkgVersion & { changelog: string }
}) {
    const [imgOpen, setImgOpen] = React.useState<boolean>(false)

    return (
        <div className="container">
            <Head>
                <title>Notex.app - RPKG Tool</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="keywords"
                    content="glacier engine, hitman, tools, resources, modding, mod, rpkg, locr, rtlv, dlge, gfxf, unpack, pack"
                />
            </Head>

            <Header />

            <ThemeProvider theme={darkTheme}>
                <main className="main">
                    <h1 className="title">RPKG</h1>

                    <h2 className="is-gray">
                        Developed by{" "}
                        <span className="is-not-gray">
                            [REDACTED]
                        </span>{" "}
                        and hosted by Notex.
                    </h2>

                    <DownloadButton versionId={latest.id} />

                    <Button
                        variant="outlined"
                        onClick={() => setImgOpen(!imgOpen)}
                    >
                        {imgOpen ? "Hide Demo" : "Show Demo"}
                    </Button>

                    {imgOpen ? <RpkgImage /> : null}

                    {versions.map((v) => (
                        <Accordion key={v.id}>
                            <AccordionSummary
                                expandIcon={<ExpandMoreIcon />}
                                aria-controls={`changelog-${v.id}-content`}
                                id={`changelog-${v.id}-header`}
                            >
                                <p>New in v{v.id}</p>
                            </AccordionSummary>
                            <AccordionDetails className="changelog">
                                <div dangerouslySetInnerHTML={{
                                    __html: v.changelog,
                                }} />
                            </AccordionDetails>
                        </Accordion>
                    ))}
                </main>
            </ThemeProvider>
        </div>
    )
}

// This function gets called at build time on server-side.
// It may be called again, on a serverless function, if
// revalidation is enabled and a new request comes in
export async function getStaticProps() {
    return {
        props: {
            versions: versions.map((v) => {
                // @ts-expect-error Yup
                v.changelog = renderToString(v.changelog)
                return v
            }),
            latest: {
                id: latest.id,
                changelog: renderToString(latest.changelog),
            },
        },
        revalidate: 900, // In seconds
    }
}
